### ISSUE TITLE
started and task properties are not set

### ISSUE THREAD

**Issue by brendan-ward** [nikmolnar/django-task-api#3]
Given a task that runs successfully, `started` and `task` are never set:

Example response
```
{
    "created": "2020-01-22T05:12:32.205814Z",
    "finished": "2020-01-22T05:12:32.312156Z",
    "messages": [],
    "outputs": {
        "message": "Run away! Run away!"
    },
    "progress": 0,
    "started": null,
    "status": "succeeded",
    "target": 10,
    "task": "",
    "uuid": "40e8872a-e27e-4e73-a38c-bd0f4cd70734"
}
```

**Comment by brendan-ward** [comment]
If the task fails, `started` appears to be set properly.

**Comment by nikmolnar** [comment]
This is fixed in the commit mentioned above. The problem was that a stale instance of `TaskInfo` was being saved after a job would complete, overwriting the start date. This was fixed by pulling a fresh instance from the database after updating the start date.
